### ISSUE TITLE
비용 최적화 문제

### ISSUE THREAD

**Issue by junah201** [junah201/Medical-Innovation#1]
최종 목표는 달에 1000원 이내의 비용 지출만으로 서비스를 유지하는 것이고, 이를 위해서 여러 서비스를 활용해서 분산해놓았습니다.

1. 데이터베이스는 카페24의 웹 호스팅에서 제공되는 DB를 사용 (이미 현 사이트가 아닌 그 전 사이트 때문에 이미 2029년까지 결제가 되어 있음)
2. 프론트엔드 배포는 Vercel을 사용
3. 백엔드 배포는 AWS lambda에 서버리스로 배포함
4. 업로드 파일 저장은 AWS S3를 사용

이 과정에서 

1. DB는 이미 결제가 되어 있어서 비용 과금 X
2.  Vercel도 무료로 배포가 되고 있으며 비용 과금 X
3.  AWS lambda도 비용 계산 상 달에 0 ~ 100원 정도의 비용만 지출
4.  AWS S3도 달에 0 ~ 500원 정도의 비용만 지출 (트레픽이 많아질 경우 증가할 수도 있지만)

하지만 카페24 데이터베이스는 기본적으로 내부에서 사용되도록 설계되어있기 때문에 외부 접속 IP를 최대 10개까지 밖에 설정할 수 있고, 모든 IP에 대해서 오픈하는 것이 불가능합니다. 따라서 AWS lambda 함수에서 DB에 접속하기 위해서는 고정 IP를 설정해야하는데 이 과정에서 AWS NET Gateway 비용이 발생합니다. 이 비용은 달에 42$ (시간 당 0.059$, `0.059 * 24 * 30 = 42.48$`)  씩 발생하는 문제가 있습니다.

따라서 생각하고 있는 해결책은 아래와 같은데 다른 해결책이 있을까요?

1 ~~카페24의 DB 접속을 모든 IP에 대해서 오픈 할 수 있는 방법을 찾는다.~~
 -> 문의를 남겨봤지만 불가능하다고 답변 받음

2 AWS lambda가 아닌 CloudType, Qoddi 등의 서비스를 이용하여 해결한다.  
 -> CloudType은 제공되는 Mysql DB가 없으며 외부 IP를 고정시킬 수 있는지 확실하지 않음
 -> Qoddi는 내부 제공 DB가 있으나 해외에 있어서 느리고, 용량이 작음, 또한 외부 IP를 고정시킬 수 있는지 확실하지 않음

3 AWS Net Gateway가 아닌 Net 인스턴스를 사용한다. 
 -> 설정 매우 방법이 복잡해보임
 -> 현 비용 보다는 낮아지긴 하지만 최종목표 비용을 초과할 것으로 보임

4 EC2 인스턴스에 연결하는 탄력적 IP는 무료이므로 DB로 가는 모든 요청을 EC2 인스턴스를 통해서 사용한다.
 -> 속도가 크게 느려지진 않을 것으로 보임
 -> 설정 방법이 복잡해보임
 -> EC2 인스턴스 비용이 부과됨

~~서버 유지비로 1년에 최대 10만원까지는 나와도 된다는 허락을 받았지만 1000원 이내로 최적화 시키고 싶음~~

**Comment by kdomo** [comment]
클라우드 타입은 Mysql대신 Mariadb를 지원하고 있습니다.
한번 생성해놓은 인스턴스의 IP는 변경되지 않습니다.(고정적)

지금까지는 클라우드 타입을 이용하는것이 가장 좋아보이지만,
2월 부터 변경된 요금제 적용이라고 하니 확인해보세용 [cloudType 요금 정책](https://cloudtype.io/pricing)

현재 데이터베이스가 문제라고 보이는데,
오라클이나 다른 곳에서 무료로 데이터베이스를 사용하는 것이 좋다고 생각됩니다. [오라클 클라우드로 평생 무료로 서버와 DB 운영하기](https://blogpack.tistory.com/935)

**Comment by junah201** [comment]
@kdomo
일단 생성해놓은 인스턴스의 IP가 고정인게 오피셜로 답변받으면 클라우드 타입으로 확실하게 이전하고
안되면 어쩔 수 없이 다른 DB 서비스를 찾아봐야할 것 같아요.
답변 감사합니다 !!

**Comment by junah201** [comment]
![image](https://user-images.githubusercontent.com/75025529/215451942-e282c6a2-ce0a-4f5e-a79b-ed26f8d10ac6.png)


클라우드타입으로 이전으로 해결하였습니다.

1. 프론트 : vercel
2. 백엔드 : 클라우드타입
3. DB : 카페24
4. 일부 함수 : aws lambda
